# Generated by Django 4.1.7 on 2023-03-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductСategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='flower',
            name='сategories',
            field=models.ManyToManyField(to='flowers.productсategory'),
        ),
    ]
