# Generated by Django 4.1.7 on 2023-02-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='flower',
            new_name='flower_id',
        ),
        migrations.RenameField(
            model_name='flower',
            old_name='sale',
            new_name='sale_id',
        ),
        migrations.AlterField(
            model_name='basket',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
