# Generated by Django 4.1.7 on 2023-03-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0008_productсategory_flower_сategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='productсategory',
            name='name',
            field=models.CharField(default=22, max_length=64),
            preserve_default=False,
        ),
    ]
