# Generated by Django 4.1.7 on 2023-03-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0012_remove_productimagemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='img',
            field=models.ImageField(default='images/34173_0.jpg', upload_to='images/sales/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
