FROM python:3.11.6 as builder

ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update -y && apt-get upgrade -y
RUN pip install --upgrade pip

COPY . /app

RUN cd /app
RUN pip install -r /app/requirements.txt --no-cache-dir

EXPOSE 8000

CMD [ "python", "/app/src/manage.py", "runserver", "0.0.0.0:8000" ]
