version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client.dev
    image: "${PNAME}-client"
    container_name: "${PNAME}-client"
    env_file:
      - docker/.env
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server.dev
    image: "${PNAME}-server"
    container_name: "${PNAME}-server"
    restart: on-failure
    env_file:
      - docker/.env
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
