# Generated by Django 4.1.7 on 2023-03-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='sex',
            new_name='is_male',
        ),
    ]
