# Generated by Django 4.1.7 on 2023-03-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_alter_buyer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='payment_method',
            field=models.CharField(choices=[('Оплата картой', 'Card'), ('Наличная оплата', 'Cash')], default='Наличная оплата', max_length=128),
        ),
    ]
